/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_championShipController','delegate/championShipDelegate'], function() {
    App.Controller.ChampionShipController = App.Controller._ChampionShipController.extend({
        language: function(){
            alert('Usted está viendo la versión en ESPAÑOL de esta página');
        },
        duracion : function(params){
            var fecha1 = params.inicio.split("/");
            var fecha2 = params.fin.split("/");
            var dias = fecha2[0] - fecha1[0];
            console.log(fecha2[0]);
            console.log(fecha1[0]);
            var meses = fecha2[1] - fecha1[1];
            console.log(meses);
            var anios = fecha2[2] - fecha1[2];
            console.log(anios);
            var duracion = anios*365 + meses*30 + dias;
            alert('El campeonato dura '+ duracion+' días.');
            return duracion;
        },
        costo : function(params){
            var costo =Math.pow(Math.E, 0.5*this.duracion(params));
             alert('El campeonato cuesta '+ costo+' .');
        }
    });
    return App.Controller.ChampionShipController;
}); 